services:
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    extra_hosts:
      - "jun-Victus-by-HP-Gaming-Laptop-16-r0xxx.local:192.168.55.114"
      - "worker1:192.168.55.158"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://192.168.55.114:9000
      - HDFS_CONF_dfs_replication=2
      - HDFS_CONF_dfs_datanode_address=0.0.0.0:9866
      - HDFS_CONF_dfs_datanode_http_address=0.0.0.0:9864
      - HDFS_CONF_dfs_datanode_ipc_address=0.0.0.0:9867
      - HDFS_CONF_dfs_datanode_use_datanode_hostname=false
      - HDFS_CONF_dfs_client_use_datanode_hostname=false
    volumes:
      - datanode_data:/hadoop/dfs/data
    network_mode: host

  spark-worker:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker
    extra_hosts:
      - "jun-Victus-by-HP-Gaming-Laptop-16-r0xxx.local:192.168.55.114"
    environment:
      - SPARK_MASTER=spark://192.168.55.114:7077
    volumes:
      - ./spark-jobs:/opt/spark-jobs
    network_mode: host

volumes:
  datanode_data:
