services:
  # ================================
  # HDFS DataNode
  # ================================
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    ports:
      - "9864:9864"
      - "9866:9866"
      - "9867:9867"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://192.168.55.114:9000
      - HDFS_CONF_dfs_replication=2
      - HDFS_CONF_dfs_datanode_address=0.0.0.0:9866
      - HDFS_CONF_dfs_datanode_http_address=0.0.0.0:9864
      - HDFS_CONF_dfs_datanode_ipc_address=0.0.0.0:9867
    volumes:
      - datanode_data:/hadoop/dfs/data
    networks:
      - pipeline-network

  # ================================
  # Spark Worker
  # ================================
  spark-worker:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker
    ports:
      - "10000:8081"
    environment:
      - SPARK_MASTER=spark://192.168.55.114:7077
    volumes:
      - ./spark-jobs:/opt/spark-jobs
    networks:
      - pipeline-network

volumes:
  datanode_data:

networks:
  pipeline-network:
    driver: bridge
